### ISSUE TITLE
Logout button is named "Remove account"

### ISSUE THREAD

**Issue by RRMoelker** [smuldr/xtime-android#9]
![logout_remove_btn](https://cloud.githubusercontent.com/assets/205326/12842013/3e913818-cbf0-11e5-8306-aa70b4fb30de.jpg)

**Comment by smuldr** [comment]
This was actually done on purpose. When you click that button you don't just log out, you remove your XTime account from the device. 

Is there a better way to phrase this?

**Comment by RRMoelker** [comment]
That seems like a technical description. To the user, for all intends and purposes, it is simply logging out right? If you want to make clear that user data is cleared from the device maybe put that as a note on the screen after clicking...? Anyway just my two cents.

**Comment by smuldr** [comment]
I think you are right. Damn those developers using their technical descriptions for everything!

While we are at it, I would like to move this functionality to the navigation drawer header. Doesn't make any sense to have this as an "action" next to the list of time sheets.
